### ISSUE TITLE
No difference between remove & subtract

### ISSUE THREAD

**Issue by johndigital** [funkhaus/wp-shopify#1]
On this line here:
https://github.com/funkhaus/wp-shopify/blob/master/js/wshop.js#L169

A cart item with `data-cart="remove"` should completely remove the line item from the cart regardless of quantity, while `data-cart="subtract"` just decrements.

It looks like `wshop.handleRemove` is defined, let's use that.

**Comment by SaFrMo** [comment]
Fixed in merge - `wshop.js` now includes:
- `handleIncrement` - adds one of an item to a cart, added with `data-cart="add"`
- `handleDecrement` - removes one of an item, added with `data-cart="subtract"`
- `handleRemove` - removes all of an item, added with `data-cart="remove"`
