### ISSUE TITLE
Allow drag and drop ordering plugins to work

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/wp-shopify#9]
Currently drag and drop plugins dont seem to work because `'hierarchical' => true,`  is not set on in the custom post type setup. I tweaked this on What Youth to test out, and it works. But then products can be nested under each other. This might not be a bad thing?

**Comment by SaFrMo** [comment]
Doesn't seem like it'd be a bad thing to me - I'll add `'hierarchical' => true` to the post type. Thanks!
